### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by heyjohnnyfunt** [Antimon2000/steganalyzer#1]
Hi. I know, that your repo  has not been updated for years, but if u r still alive, could you explain please, how to use your program? For steganalysis in particular. Thank's!

**Comment by Antimon2000** [comment]
Hi,

yep, the repo is not in development anymore. It anyway is not more than a prototype that was supposed to show how the architecture of a steganalysis tool that accepts many different input files could look like. However, the real detectors have *not* been implemented so you won't be able to perform any actual steganalysis.

**Comment by heyjohnnyfunt** [comment]
doh.. thank's for the response!

**Comment by Antimon2000** [comment]
No worries. If there is a specific type of document that you want to perform steganalysis on, I might be able to tell you what to look for. And of course, if you would like to contribute to this repository I could point you to the scientific papers that describe how to implement several steganalysis techniques :)

**Comment by heyjohnnyfunt** [comment]
Wow, thank's! But I think I've got not enough time for writing an implementation :( I've been searching for a steganalysis tool, that can perform image(s) checking and simply say, that there might be hidden data. I found [StegExpose](https://github.com/b3dk7/StegExpose) and [StegDetect](https://github.com/abeluck/stegdetect) repos, but the first one is the only one works and works with a lot of false-positive errors, and the second is not compiling for me. All in all there are still only two utilities I found... That's why I've found out your repo :)
If you can give me a tip about this, I would really appreciate that

**Comment by Antimon2000** [comment]
Hey, sorry, I totally forgot about your message!

As far as I know there is no tool that detects a large number of steganography techniques out of the box. You should rather try different specialized detection programs. StegExpose is for LSB steganography which is easily detectable for relevant embedding rates, hence this will only be used by beginners.

More serious image steganography methods are F5 and OutGuess. Therefore you once again should try to get StegDetect to work. On Ubuntu it's even accessible through the package manager - no need to compile the stuff on your own! Just type `sudo apt-get install outguess` into the console and you're ready to go.

Of course, there are even more advanced steganographic techniques but I'm afraid the published analysis algorithms won't be easier to handle than compiling Outguess. If you're interested anyway, you should search for "Ensemble classifiers". One of the experts in this field is Jessica Friedrich. She and her staff publish their research code on [1], good luck!

[1] http://dde.binghamton.edu/download/ensemble/
